### ISSUE TITLE
Intro for Cornell Students.

### ISSUE THREAD

**Issue by iHiD** [exercism/automated-analysis#1]
Hello @exercism/cornell-cs5152-2019 👏 

This is the repository we'll be using for planning out the general static analysis work on Exercism.

As a first step, when you've decided languages, please let us know here and we'll create Issues for you and the relevant maintainers to discuss the plan.

Please take some time to familiarise yourself with Exercism - both the project (https://exercism.io - sign up and take a track!) and the open source world (https://github/exercism/exercism is a good place to start).

@kytrinyx @nicolechalmers @ccare and @kntsoriano will all be working on the static analysis alongside you, as well as @petertseng and whichever maintainers want to get involved. We're a friendly bunch so please reach out with any questions etc :)

**Comment by kytrinyx** [comment]
It looks like the languages picked are Python and Java.

**Comment by kntsoriano** [comment]
Hello @exercism/cornell-cs5152-2019! Would be happy to help with any questions :)
