### ISSUE TITLE
[New Representer] Nim 

### ISSUE THREAD

**Issue by ynfle** [exercism/automated-analysis#101]
Hello!

I would like to start a representer for Nim. 

I have started to work on the represented for Nim [here](https://github.com/ynfle/nim-representer).

**Comment by ErikSchierboom** [comment]
@iHiD This is for you to look at :)

**Comment by iHiD** [comment]
Sorry it took me ages! https://github.com/exercism/nim-representer

**Comment by ynfle** [comment]
No problem

Looking forward! 😃
