### ISSUE TITLE
[New Representer] Rust

### ISSUE THREAD

**Issue by seanchen1991** [exercism/automated-analysis#102]
Hello :wave:

 I noticed there wasn’t a representer for Rust, so I’d like to help work on it. I’ve spent some time exploring and thinking about what open-source Rust libraries that could be leveraged for this sort of task (the `syn` crate is at the top of my list right now), but other than that, I don’t really have any other credentials, other than just the fact that I’m interested in this problem 🙂

**Comment by ErikSchierboom** [comment]
Great! @iHiD will create a repo for you.

**Comment by iHiD** [comment]
Hello. There is a rust analyzer: https://github.com/exercism/rust-analyzer

Did you mean a representer?

**Comment by seanchen1991** [comment]
Yes, I meant representer 🙂

**Comment by iHiD** [comment]
Great! Here you go: https://github.com/exercism/rust-representer :D
