### ISSUE TITLE
Persisted state

### ISSUE THREAD

**Issue by razum2um** [exercism/automated-analysis#15]
I *highly* value the stateless approach to shell-script+solution-directory, but in order to properly implement #5 a running checker should somehow consume and reduce over all submitted solutions+aprovements -> and consequently store/load it somehow. 

If you saw #12 with docker suggestion I think an additional persisted volume could be fine. Obvious downsides are state corruption / maybe need for "reset". Maybe this disk space should be transactional (e.g. vcs committed outside after successful check / able to reset).

**Comment by ErikSchierboom** [comment]
> [...] a running checker should somehow consume and reduce over all submitted solutions+aprovements

Ehm, could you explain why this is necessary?

**Comment by razum2um** [comment]
As mentioned before, I'd like to match ASTs not only from a single example, but collect everything what have been and will be approved

**Comment by ErikSchierboom** [comment]
> [...] but collect everything what have been and will be approved

Ah, but there might be other ways to get this! For example by having the option to do an export or something like that.
