### ISSUE TITLE
Pass track into the analyzer

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/automated-analysis#18]
According to [the interface](https://github.com/exercism/automated-mentoring-support/blob/master/docs/interface.md), and the [sample `analyze.sh`](https://github.com/exercism/ruby-analyzer/blob/master/bin/analyze.sh#L4), the analyzer will be called with the `exercise-slug` and root directory of the submission.

I propose adding the track explicitly:

- This allows for languages that can be expressed using the same ast or very similar ast to use the same analyser, very DRY.
- This allows for a defensive guard to bail out early if the script is called incorrectly.

Two alternative solutions:
- optionally receive the track via the slug: `typescript/two-fer`.
- when languages want to use the same analyser, they only have a bootstrap script that sets an option or environment variable and then calls the general analyser.

**Comment by iHiD** [comment]
Let's have the discussion on #19 :) To quote what I said there for reference:

> I'm more than happy to create JS and TS repos for you. I'm not sure whether having a central one is a good or bad idea in the longrun. I would have thought that the mentoring tips would diverge almost immediately?

**Comment by SleeplessByte** [comment]
Closed per #19
