### ISSUE TITLE
[New Analyzer] estree (javascript + typescript)

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/automated-analysis#19]
I've created an initial estree analyzer that can handle any estree (so currently on exercism `javascript` and `typescript`). Id love to have this as a base, and two "per-exercise" implementations/repos, one for JS and one for TS.

You can find the analyzer at [SleeplessByte/exercism-estree-analyzer](https://github.com/sleeplessByte/exercism-estree-analyzer).

_Unfortunately_ the javascript `two-fer` is not up to date with the spec and doesn't expect a default argument. However, I've written the analyzer in such a way that it expects it, which results in [this output](https://github.com/SleeplessByte/exercism-estree-analyzer/tree/master/test/solutions/two-fer/df3bb5d7131c44ea9c62206cc8d6c225) for "older" versions of the tests.

**Comment by iHiD** [comment]
I'm more than happy to create JS and TS repos for you. I'm not sure whether having a central one is a good or bad idea in the longrun. I would have thought that the mentoring tips would diverge almost immediately?

@kytrinyx Thoughts?

**Comment by SleeplessByte** [comment]
I've written most of the notes for both. In most cases the TS ones are js plus additional rules. But I think with the restructuring of the track this will become more diverting; therefore my current suggestion would be:

exercism/javascript-analyzer
exercism/typescript-analyzer

However, there is some duplication then. Alle the config, base class and output logic would be duplicated.

I'm happy maintaining two repos!

**Comment by iHiD** [comment]
Great!

In which case, can we close #18 as something that doesn't need to happen? (as there will be two separate analyzers)?

**Comment by iHiD** [comment]
Here you go: 

https://github.com/exercism/typescript-analyzer
https://github.com/exercism/javascript-analyzer

:)
