### ISSUE TITLE
Data Flow

### ISSUE THREAD

**Issue by iHiD** [exercism/automated-analysis#21]
This is a (written) flow-chart of how data will be passed around. Any general comments are welcome before I turn this into a document for this repo (where y'all can help fix my awful typos etc :) )

### Website 
- [x] Receives an iteration from a user via the CLI
- [x] Uploads submitted code to a private s3 bucket using the path `submissions/:id/iterations/:id/...`
- [x] Files a message via Propono to say the iteration has been submitted

### Orchestrator
- [x] Receives messages via Propono
- [ ] Checks that an analyzer exists for the language
- [x] Downloads the files from s3 into a local directory
- [x] Runs the language-specific analyzer docker command with the exercise slug and a link to the directory

### Analyzer
- [x] Checks the code and writes an analysis.json into the directory.
- [x] Can create a data file called `analysis.out` that contains any stack trace or internal messages for maintainers (to be named).
- [x] Returns a status of success/failure of the process

### Orchestrator
- [x] If the analyzer has been successful, writes analysis.json to s3.
- [x] If the analyzer has been successful, fire a propono message saying that the analysis has been successful with the contents of the json file.
- [x] If the analyzer has failed, fires propono message saying the analysis has failed.
- [ ] In either situation the analyzer writes metadata about the analysis to s3 (e.g. CPU/Mem usage, whether the process finished or was killed, stack trace in error situation, command line output, etc), along with the data file from the analyzer. These can be used by maintainers to monitor/improve their situation.

### Website
- [ ] Receives propono message about the analysis and acts accordingly (to be fleshed out later but irrelevant for this issue)

**Comment by petertseng** [comment]
Even though I don't know what Propono is, from my reading of this written form, this lack of knowledge did not appear to impede my overall understanding of the flow; I simply assumed "Propono is something where things can send and receive messages" and the rest remained understandable. So it is likely that no action is needed in response.

However if there is an important detail that is useful to note about Propono (I can't think of any, but you never know what unknown unknowns there are), you might consider making that known somehow.

**Comment by iHiD** [comment]
@petertseng Good point. Thanks. Some info that might help add colour:

- To quote the README, "Propono is a pub/sub gem built on top of Amazon Web Services (AWS). It uses Simple Notification Service (SNS) and Simple Queue Service (SQS) to seamlessly pass messages throughout your infrastructure.". It basically passes messages between apps through a publish/subscribe arctiteture.
- I'm the maintainer of it
- It's pretty mature and has handled tens of millions of messages without issue.

**Comment by pgaspar** [comment]
>  Returns a status of success/failure of the process

What does "failure" look like here? No `analysis.json` is written?

**Comment by tehsphinx** [comment]
I thought we specified it somewhere to mean: exit code unequal to zero.

But now I can't find that anywhere in the interface definition @iHiD.
