### ISSUE TITLE
[New Analyzer] Python

### ISSUE THREAD

**Issue by xitanggg** [exercism/automated-analysis#22]
@TreyAguirre and I'd love to create a Python analyzer. We just made our first implementation of the static analysis tool for two_fer and it can be found at https://github.com/TreyAguirre/Python-Two-Fer. The structure and interface have been modified to resemble the current ruby analyzer interface. Any feedback and suggestion are appreciated👍😃

**Comment by iHiD** [comment]
Awesome. I'll get this set up for you :)

**Comment by iHiD** [comment]
@xitanggg @TreyAguirre You both have access to https://github.com/orgs/exercism/teams/python-analyzer now. Please could you push your code up there :)
