### ISSUE TITLE
[New Analyzer] Java

### ISSUE THREAD

**Issue by Smarticles101** [exercism/automated-analysis#23]
I'd like to start work on a java analyzer. I help maintain the java track :)

**Comment by iHiD** [comment]
@exercism/cornell-cs5152-2019 How are y'all getting on with the Java analyzer?

**Comment by iHiD** [comment]
@Smarticles101 I've created a repo and give you write permission. (https://github.com/exercism/java-analyzer)

@petertseng @exercism/cornell-cs5152-2019 Could you please discuss with @Smarticles101 what you've done already and agree how to get it into that repo please? If you need/want permission to write to it, please just let me know.

**Comment by Smarticles101** [comment]
@exercism/cornell-cs5152-2019 I just uploaded an initial implementation of the two-fer analyzer at https://github.com/exercism/java-analyzer. If y'all have any improvements could you pr those? Feel free to radically redesign stuff if you feel like ;)

**Comment by iHiD** [comment]
I'm closing this due to fact I've created the repo and there's not an active discussion :)
