### ISSUE TITLE
Number of returned comments

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/automated-analysis#28]
How many comments should an analyzer return? Only one, more than one? There are clear benefits to both approaches. Only one comment prevents the student from being overwhelmed, but could possibly lead to more iterations than immediately returning all comments. One thing to also consider is that I expect the comments to be more expansive than what they might be now. A human mentor is less likely to post large comments over and over (unless they have stored them somewhere), whereas an automated mentor would not have such problems.

**Comment by SleeplessByte** [comment]
I generally do long form comments when I mentor as a human -- and I think returning only one comment will be very detrimental in a lot of cases:

I think the best approach is to group comments. If there is something structurally wrong, which means the tests won't run, you can give them that comment (or set of comments):
- When you're trying to use an enumerator / comprehension, and have a comment to use `map` and have a comment to use `reduce`, I would always send them both.
- When they don't use a default value parameter and don't use template literals/string interpolation, I would always send them both comments, _because that's what I do when I mentor_.

I don't think we want students to come back to exercism making the single change, and then getting rejected again, and again, and again, and again.

**Comment by tehsphinx** [comment]
When mentoring I definitely give all comments. That gives the student a lot of information but prevents them from having to wait again.

For automation we could do it differently because we will have very fast response times.

My preference still would be to give the student all the information at once. I would feel very stupid having to submit e.g. 5 iterations because the comments came one ofter another. And if I finally get approval with another comment I could improve on -- I wouldn't: just because it adds even more iterations. That is my personal feeling on the subject.

**Comment by tehsphinx** [comment]
One more note: I have seen students (2 or 3) snap at their mentor because they came with another thing to improve on the 5th iteration. Their argument was: If you would have told be from the beginning it would be fine, but not on the 5th iteration!

**Comment by kotp** [comment]
The snap about changes on the 5th iteration may not be appropriate, as in the 1st or 2nd iteration, you may be guiding them to finally get to that point in the 5th iteration to be able to make the change that appears in the 6th.  Leap year can be like this, where you want to guide them to the point, but you want them to learn why, and finally, something clicks in place to be able to get to that solution.  The state of the solution may have been able to get there on the 2nd iteration, from a comment in the first, but the reasoning may be missed.  

I think that this is the difference between automated mentoring and in person mentoring, where you can gauge what is missing in the knowledge, and what has been considered, and can adjust if you approve before or after the changes are made (or perhaps never made, as they do get it, it just isn't demonstrated in the code after the realization.)

**Comment by ErikSchierboom** [comment]
Personally, I usually like the "one comment at a time" approach. Focus on one thing, and fix that. I do admit that this is probably not what everyone prefers though, which is why I created this issue.

**Comment by SleeplessByte** [comment]
I would personally not even ben on any mentored track if I'd only got to fix one thing to fix each time, but that's mainly because of the _time_ inbetween. If I get an auto-mentored response within minutes, that _would_ change my feeling.

**Comment by ErikSchierboom** [comment]
> If I get an auto-mentored response within minutes, that would change my feeling.

Precisely. And that is why I feel thank we should at least consider returning just a single comment.

**Comment by SleeplessByte** [comment]
I would still suggest we group some of the comments that are similar; but yes. If the analyzing is _almost synchronous_, I can see single-ish commentary being a possibility.

**Comment by tehsphinx** [comment]
I feel we are talking about the edge cases here where actually one comment after another does make sense. To get away from the edge cases let me bring a typical example from Go `twofer`:

An actual students solution:
```go
package twofer

import "fmt"

// ShareWith shares with provided name.
func ShareWith(name string) string {
	if len(name) == 0 {
		name = "you"
	}
	return fmt.Sprintf("One for %v, one for me.", name)
}
```

If I was the student I would really feel annoyed if I got the comments to it in 3 steps:

- to check if a string in Go is empty you can just do `name == ""`. A string in Go cannot be nil so taking the `len` of it is not necessary.
- Tip: any type of value in Go can be printed using the format character `%v`. However, there's also a different format for each type (for example `%s` for strings). The type specific formats also offer more options for formatting that type. For example the format `%f`, for `float` values, can also specify the precision: `%.2f`.
- Community style says that a package in Go should have a comment. For more details, have a look at the comments section below.


---
Go has [great guidelines](https://golang.org/doc/effective_go.html) about ...

---

**Comment by tehsphinx** [comment]
I just don't think we can make a general rule...

**Comment by ErikSchierboom** [comment]
> I just don't think we can make a general rule...

Well, I still think we should try :) Returning just one comment or returning many comments are completely different experiences for the student. In essence, we should be doing what is best for the student, which is why I'm really interested in hearing @kytrinyx, @iHiD and @F3PiX's thoughts.

**Comment by SleeplessByte** [comment]
Well , perhaps there is a midway where we have a rule _per language_?

**Comment by ErikSchierboom** [comment]
That is an option!

**Comment by SleeplessByte** [comment]
I think this is now covered by #39 

The consensus is: 
- the amount doesn't matter, 
- it will depend on the product team discussion results in terms of what will be displayed
- they should always attempt to guide a student from a disapproved state to approved state

**Comment by ErikSchierboom** [comment]
I agree.
