### ISSUE TITLE
How to handle different types of formatting 

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/automated-analysis#31]
Some languages have a pre-defined formatting scheme. Examples are Elm and Go. For these languages, it makes sense that a solution with non-standard formatting results in comments being made by the analyzer. But how should we deal with languages that don't have such formal formatting rules? E.g. for C# there are no such predefined rules, except for some very [general ones](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions). There are of course some _conventions_, stylistic choices that lots of people use, but nothing definitive. For such languages, should the analyzer just ignore the formatting?

**Comment by SleeplessByte** [comment]
I think it should handle it like we would if we were to mentor it as a human.

In JS and TS that means we wouldn't comment on it. Ever. So therefore I don't think the analyzer should.

**Comment by tehsphinx** [comment]
I think there are still some general rules about indentation for example. Not indented blocks of code are a "no go" in any language.

**Comment by SleeplessByte** [comment]
Actually that's not true. There are languages where whitespace is significant, and thus indentation is mandatory, there are languages where whitespace is not, but it's generally agreed upon that you need indentation, but there are also languages where whitespace is _at will_ and there is not good rule around it.

II don't think there is a good way to enforce / analyze this in JavaScript or TypeScript, even though there _are_ community standard on it, but there are too many permutations, and too many mutually exclusive stylistic choices to pick something.

Even in Ruby, take the `case` blocks:

```ruby
case expression
  when expression
    block
    break
  when expression
    block
    break
  else
   block
end 
```

```ruby
case expression
when expression
  block
  break
when expression
  block
  break
else
  block
end 
```

```ruby
case expression
when expression
  block
break
when expression
  block
break
else
  block
end 
```

These are all _equally_ valid, and depend on the styleguide of the _project_, not the language.

**Comment by ErikSchierboom** [comment]
> I think it should handle it like we would if we were to mentor it as a human.

I like this!

**Comment by tehsphinx** [comment]
@SleeplessByte Sure, I am aware of that. Have been programming with languages like these for 20+ years (yup... i'm that old).

Talking here about no indentation at all (which I have seen in solutions) or inconsistent indentations (which happens even more often). I know it will be hard but if possible (with reasonable effort) I think it should be caught.

Maybe it is even possible to create an algorithm that checks indentation consistency across languages that way not everyone has to reinvent the wheel. Or maybe there even is something out there...

**Comment by iHiD** [comment]
[This](https://github.com/exercism/ruby-analyzer/blob/master/lib/analyzers/two_fer/analyze.rb#L188) is currently what we're doing for Ruby.

I think the following is the general guidance, but this is a perfect example of what I want from our slack discussion later. Bring some complex examples for us to discuss :)

- If it's a rule in a language, we enforce it as a rule (e.g. Go/Ruby)
- If there's a normal that's not a rule, then we add a comment.
- If there's no normal/rule, then we don't bother commenting.

**Comment by SleeplessByte** [comment]
I think this is covered by #39
