### ISSUE TITLE
[New Analyzer] Perl5

### ISSUE THREAD

**Issue by rfilipo** [exercism/automated-analysis#34]
I'm a mentor and maintainer of Perl5 track.
About me:
[Monsenhor resumé](http://kobkob.org/monsenhor/)

Very excited on this matter, I began a WIP analyzer prototype for Perl5 at:
[perl5-analyzer](https://github.com/rfilipo/perl5-analyzer)

It uses "Perl::Critic" as the framework for testing and analyzing codes. Each exercise will implement a new policy with possible specifications, comments, violations, and pieces of advice, helping and teaching the student.

**Comment by iHiD** [comment]
Done here: https://github.com/exercism/perl5-analyzer - you have write access. Thanks and have fun! :)
