### ISSUE TITLE
[New Analyzer] Erlang

### ISSUE THREAD

**Issue by NobbZ** [exercism/automated-analysis#37]
I'd like to create an analyzer for erlang.

I'm currently the maintainer of the erlang track and a mentor as well.

I already developed a small testing tool for erlang which enhences the standard testing tool a little bit, such that we are able to adhere to some of the exercism specialties, like the example file.

I planned to extend this tool to also issue some generic lints, but failed to integrate it properly.

So far, `two-fer` is a side exercise for erlang, and probably the amount of submissions might be pretty low.

My plan is to move `two-fer` to core as a second exercise such that the analyzer and `two-fer@core` go live approcimately in the same week (with moving `two-fer` to core a bit earlier than activating the anylizer)

I have no example implementation right now though, but I should be able to create one during the next couple of days if this is necessary in advance.

**Comment by iHiD** [comment]
Thanks @NobbZ. That's exciting.

Analyzer here for you: https://github.com/exercism/erlang-analyzer and I've sent you the two-fers on Slack :)
