### ISSUE TITLE
Hints on twofer (Go track)

### ISSUE THREAD

**Issue by tehsphinx** [exercism/automated-analysis#4]
### A summary of what exalysis currently adds as hints on `twofer`

**Generalised solution**
- I see you referenced the names `Alice` and `Bob` directly in your code. This is a good first step! Can you make the `ShareWith` function work with any name supplied to it?

  [Template](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/tpl/generalize-name.md)
  [Exalysis Code](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L99)

**Minimal conditional**
- Currently you are repeating most of the output string. This is OK, but in general, Go programmers try to avoid duplicating code where they can avoid it. Can you work out how to restructure your code so that you don't repeat yourself?

    (It may sometimes be better to duplicate small things than to introduce unnecessary complexity just to avoid duplication. A Go proverb says "A little copying is better than a little dependency".)

  [Template](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/tpl/minimal-conditional.md)
  [Exalysis Code](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L92)

**String building**
- I see you are using `+` to concatenate the string. That is perfectly legit! If you didn't know about the `fmt` package, check it out. It can do lots of things related to string formatting, including concatenating strings.

    (Using `+` is probably the right choice here. I just wanted you to know about `fmt`, because it's awesome, and you'll be using it a lot.)

  [Template](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/tpl/plus-used.md)
  [Exalysis Code](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L40)

- I spotted that you're using `strings.Join` to build the string. That works, but you might like to look at the `fmt.Sprintf` function instead; it's a very powerful way of building up strings from multiple pieces.

    (When you only need to concatenate strings, you can use the `+` operator to do this instead of calling `fmt`.)

  [Template](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/tpl/strings-join.md)
  [Exalysis Code](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L32)

- Tip: any type of value in Go can be printed using the format character `%v`. However, there's also a different format for each type (for example `%s` for strings). The type specific formats also offer more options for formatting that type. For example the format `%f`, for `float` values, can also specify the precision: `%.2f`.

  [Template](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/tpl/use-string-placeholder.md)
  [Exalysis Code](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L64)
    
**Wrong formatting** will trigger a `gofmt` comment:
- Code formatting in Go is very important to the community. Take a look at `gofmt` and run it on your code. Your editor or IDE should be able to do this for you automatically:

    - Visual Studio Code has [great Go support](https://code.visualstudio.com/docs/languages/go)

    - Vim also has a [fantastic Go extension](https://github.com/fatih/vim-go)

    - [Jetbrains Goland](https://www.jetbrains.com/go/) is an entire IDE for Go

  [Template](https://github.com/tehsphinx/exalysis/blob/master/gtpl/tools/not_formatted.md)
  [Exalysis Code](https://github.com/tehsphinx/exalysis/blob/master/exam/gofmt.go#L16)

Package/function **comments**
- Community style says that X in Go should have a comment. For more details, have a look at the comments section below.

  [Template](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/tpl/missing-comment.md)
  [Exalysis Code](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L78)

- The comment describing the X isn't quite in the standard format. The section on comments below may help you fix this.

  [Template](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/tpl/wrong-comment-format.md)
  [Exalysis Code](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L78)

- Don't forget to delete and replace all the stub comments with real comments. You might be surprised at how important accurate, helpful comments are to Go developers. This is a great guide to writing good comments: [Effective Go: Commentary](https://golang.org/doc/effective_go.html#commentary). Remember, the `godoc` tool will produce documentation from your code comments automatically. See [godoc.org](https://godoc.org) for examples of what this looks like.

  [Template](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/tpl/stub.md)
  [Exalysis Code 1](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L78), [Exalysis Code 2](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L130), [Exalysis Code 3](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L153)

Wrong/missing **comment** also triggers a hint on `golint`:
- There's a great tool called [`golint`](https://github.com/golang/lint) which will examine your code for common problems and style issues. Try running `golint` on your code, e.g.: `golint two_fer.go`; it will make some useful suggestions for you.

    It's a good idea to always check your code with `golint` (or configure your editor to do it for you). When you're writing Go software for production, many build pipelines will automatically fail if the code doesn't pass `golint` (and `gofmt`). You can avoid this by linting code yourself prior to submitting it.

  [Template](https://github.com/tehsphinx/exalysis/blob/master/gtpl/tools/not_linted.md)
  [Exalysis Code](https://github.com/tehsphinx/exalysis/blob/master/exam/golint.go#L20)

**Comment** section added if comments are missing or have the wrong style:

---
Go has [great guidelines](https://golang.org/doc/effective_go.html) about how to write comments. There's a standard format you can use for documentation comments, which can then be turned into beautiful documentation automatically by the `godoc` tool.

The package comment should start with the word `Package` followed by the package name, like this:

```go
// Package cook provides handy conversion methods for units typically used in recipes.
package cook
```

For exported functions, methods, constants, and package variables, the comment should start with the name, and continue with a verb phrase:

```go
// TbsToMl converts tablespoons to milliliters.
func TbsToMl(tbs int) int {
	// ...
}
```

The [CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences) wiki further specifies that doc comments should be full sentences, ending with a period.

In addition to optimizing for readability, following the recommendations improves how your code looks in [Go's documentation tools](http://whipperstacker.com/2015/09/30/go-documentation-godoc-godoc-godoc-org-and-go-doc/) such as [godoc.org](http://godoc.org), `godoc`, and `go doc`.

Take a moment to read the section on doc comments in the official style guide, [Effective Go](https://golang.org/doc/effective_go.html) to see the reasoning behind these choices.

---

  [Template](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/tpl/comment-format.md)
  [Exalysis Code 1](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L78), [Exalysis Code 2](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L130), [Exalysis Code 3](https://github.com/tehsphinx/exalysis/blob/master/track/twofer/twofer.go#L163)

We also add a [**general introduction** to the Go track](https://github.com/tehsphinx/exalysis/blob/master/gtpl/topic/hints.md) instead of a random tip on `twofer`.

  [Exalysis Code](https://github.com/tehsphinx/exalysis/blob/master/suggestion.go#L90)

**Comment by tehsphinx** [comment]
As far as I know we mostly approve unless the solution doesn't work or was not generalized. (At least that is what I do.)

**Comment by tehsphinx** [comment]
There are 2 things I am thinking of adding:
- introducing an extra variable on `twofer` is not necessary in Go as Go does not pass by reference. A hint on that and an explanation might be useful if people add a new variable instead of overwriting `name` if it is empty.
- I have seen solutions using an additional function which makes it only harder to read. A Comment might be useful to point that out.

**Comment by iHiD** [comment]
This is super helpful. Would you mind updating your OP with links to where you check for each of those things pls? It would be a really nice reference for @kytrinyx and I to look at when considering the Ruby one :)

**Comment by kytrinyx** [comment]
I agree on those additional hints, @tehsphinx. When I review manually I always comment on those two things.

**Comment by tehsphinx** [comment]
@iHiD Did you have something like this in mind?

Note: There are still some known false positives and cases that are not caught be exalysis. That wasn't so bad since the mentor still had a look at it's output anyway.

On a completely automated tool I still wonder how we should identify good solutions. **The absence of improvement suggestions does not infer a good solution.**

I guess we would need a way to define what ASTs a good solution can have.

But maybe you have better ideas on that problem.

**Comment by kytrinyx** [comment]
> I guess we would need a way to define what ASTs a good solution can have.

That's what I've been thinking. That there are some ASTs that we know are good, and we approve those. Then as we get more data, we might discover that there are more ASTs that are "typical" of good solutions, and we can add those to the mix.

**Comment by tehsphinx** [comment]
@kytrinyx, @iHiD: Had a try at the AST comparison algorithm. See #5.

**Comment by kytrinyx** [comment]
@tehsphinx That is really useful! I haven't taken the time to play with this to digest it properly, but I think that the observations you've made are spot on, and highlight some potential areas that we'll need to experiment with to ensure we don't (a) end up painting ourselves into a corner where we have to add a never-ending list of good solutions, or (b) accidentally approve a solution that is wildly off.

**Comment by ErikSchierboom** [comment]
This is really helpful!

**Comment by ErikSchierboom** [comment]
> That's what I've been thinking. That there are some ASTs that we know are good, and we approve those. Then as we get more data, we might discover that there are more ASTs that are "typical" of good solutions, and we can add those to the mix.

Yeah, this is also how I envision the C# analyzer progressing.
