### ISSUE TITLE
Initial checking of every automated answer

### ISSUE THREAD

**Issue by tehsphinx** [exercism/automated-analysis#40]
I'd be happy to get a notification on every single solution the `go-analyzer` does something to until I feel good about it performing correctly.

Some ideas:
- only get notifications when it was applied to the exercise
- get notification on every solution the with the result of the analyzer
- in exercism.io notifications
- or per mail

Bonus would be if I was able to filter this by exercise and status (approve, etc) so if I am happy about a certain status I can filter it out... or later if I'm happy with `twofer` but want to keep an eye on `hamming`, etc.

Another good thing would be if I would get a note on comments the student provides after -- or would that end up in the queue anyway?

**Comment by iHiD** [comment]
I think we need a section on the website for this where you can access solutions and data (including analysis.json and analysis.out), and filter by these things.

**Comment by Smarticles101** [comment]
A section on the website would be great. Some stats about performance and fail rate would be great too.

**Comment by tehsphinx** [comment]
That would be much better of course if it is not much more work.
