### ISSUE TITLE
Dockerfile and entrypoint

### ISSUE THREAD

**Issue by NobbZ** [exercism/automated-analysis#41]
In the `docs/interface.md` it is stated:

> An analyzer should provide an executable script at `bin/analyze.sh` which will be called by the external orchestrator.

In the contaext of the orchestrator is using `docker` to orchestrate, I think this might lead to non-idiomatic usage of docker.

Instead I think, the `Dockerfile` should provide an entrypoint, which is set up to handle the arguments in the specified way.

Then I could do eg this for the erlang-analyzer:

```Dockerfile
ENTRYPOINT ["/opt/analyzer/bin/erlang_analyzer", "/opt/analyzer/analysis.json", "/opt/analyzer/analysis.out"]
```

Asuming the orchestrator does a `docker run`, then the `docker run exercism.io/erlang_analyzer:latest two-fer /tmp/123` should call my analyzer with appropriate values, see my example shell session as an example:

```plain
$ cat Dockerfile
FROM alpine:latest

ENTRYPOINT ["echo", "1", "2"]
$ docker run example
1 2
$ docker run example 3
1 2 3
```

**Comment by NobbZ** [comment]
Addendum: If we adhere to this rule, then this puts me close to a position, where I could do a final `FROM scratch` stage.

To achive that final goal, I had to do some architectural changes, but it should be possible as a mid to long term goal.

**Comment by tehsphinx** [comment]
Have you seen https://github.com/exercism/automated-mentoring-support/blob/master/docs/docker.md?

Also note my dismissed PR for an ENTRYPOINT in the docker file: https://github.com/exercism/automated-mentoring-support/pull/33

**Comment by NobbZ** [comment]
Yes, I have read the `docker.md` as well, but it did not answer anything of my points, but pointing me to it here, might show, that current docs are a bit cluttered ;) eg. in the `docker.md` there is no hint whether `analyze.sh` is called by fully qualified path, or relative from the working dir. Especially the mentioning of setting `WORKDIR` correctly, makes me assume that actually `bin/analyze.sh` is run, but #33 says it `/opt/analyzer/bin/analyze.sh` (fully qualified).

Since #33 (which I haven't seen before) tells us, that `docker` isn't actually used for anything but building the image, I'm fine with it, but then documentation should be much more clear about how the container is actually run and that the container is only a unit of isolation and not actually run by docker.

**Comment by tehsphinx** [comment]
A PR would be helpful. I already created one for `interface.md` to point to `docker.md` instead of providing half the information.

More explanation in `docker.md` would be good. I agree.

**Comment by iHiD** [comment]
The world has changed a lot since this so I'm going to close it.
