### ISSUE TITLE
Deploying analyzers for approving Two-Fer

### ISSUE THREAD

**Issue by iHiD** [exercism/automated-analysis#44]
Hello everyone.

This is the tracking issue for deploying the analyzers. When your analyzer has TwoFer auto-approving, and you have a Dockerfile in your repo that you're happy with, please add a comment here and @ccare will get it live :)

**Update:** Please could you also PR to https://github.com/exercism/analyzer-orchestrator/blob/master/lib/orchestrator/analyze_iteration.rb#L3 with which exercise(s) are going live. Please keep the array alphabetical. Thanks :)

### Deployed
- [x] Ruby
- [x] C#
- [x] Go
- [x] JavaScript
- [x] TypeScript
- [x] Rust
- [x] Python
- [x] Java
- [x] Scala

**Comment by tehsphinx** [comment]
adding a comment here 😃

**Comment by Smarticles101** [comment]
Dropping a comment for java :)

**Comment by SleeplessByte** [comment]
JavaScript is here: https://github.com/exercism/javascript-analyzer/blob/master/Dockerfile

**Comment by ZapAnton** [comment]
Adding a comment for Rust, `reverse-string` exercise (https://github.com/exercism/rust-analyzer/blob/master/Dockerfile)

**Comment by SleeplessByte** [comment]
TypeScript is also here: https://github.com/exercism/typescript-analyzer/blob/master/Dockerfile

**Comment by iHiD** [comment]
@Smarticles101 @SleeplessByte @ZapAnton I've added y'all to the list above. Should get done Thus/Fri this week. Please could you also PR to https://github.com/exercism/analyzer-orchestrator/blob/master/lib/orchestrator/analyze_iteration.rb#L3 with which exercise(s) are going live. Please keep the array alphabetical. Thanks :)

**Comment by SleeplessByte** [comment]
https://github.com/exercism/analyzer-orchestrator/pull/13 added `java`, `javascript`, `rust` and `typescript`.

cc @Smarticles101 @ZapAnton

**Comment by iHiD** [comment]
@SleeplessByte You're going to hate me but any chance you could do them as seperate PRs please? As then we can deploy and test each one in turn. Sorry!

**Comment by SleeplessByte** [comment]
Haha don't hate it. Easy enough.

https://github.com/exercism/analyzer-orchestrator/pull/14
https://github.com/exercism/analyzer-orchestrator/pull/15
https://github.com/exercism/analyzer-orchestrator/pull/16
https://github.com/exercism/analyzer-orchestrator/pull/17

**Comment by TreyAguirre** [comment]
Python is here: https://github.com/exercism/python-analyzer/blob/master/Dockerfile

**Comment by PierreLeresteux** [comment]
I think I have a first version of the Kotlin Analyzer (two fer - approve optiomal/with comments/disapprove/refer to mentor) ... 
Next week I'll be OFF, so maybe it's better to wait ... I'm ok if someone will review

**Comment by SleeplessByte** [comment]
@PierreLeresteux invite me and I'll review :)

**Comment by PierreLeresteux** [comment]
> @PierreLeresteux invite me and I'll review :)

Don't know how to do this (and not sure to have necessary rights ! ) ... Project is already in exercism github team : https://github.com/exercism/kotlin-analyzer

**Comment by NobbZ** [comment]
@PierreLeresteux to invite someone to review, you need to create a PR and use the right side menu to request review.

Especially for the docker file you are not allowed to merge without a review by @ccare once your analyzer has got deployed and activated.

**Comment by PierreLeresteux** [comment]
Like I said : I'm OFF this week... I'll try to do this next week :smiley: Thanks

**Comment by NobbZ** [comment]
That's totally fine, take your time. I'm just answering now, because I'm not off this week and would forget to write if I were waiting to write.

Holen Sie sichOutlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by SleeplessByte** [comment]
@PierreLeresteux enjoy your time off! I will review this and put the commentaries in an issue.

**Comment by ricemery** [comment]
I have Scala - two-fer analyzing...
https://github.com/exercism/scala-analyzer/blob/master/Dockerfile
