### ISSUE TITLE
[New Analyzer] Rust

### ISSUE THREAD

**Issue by ZapAnton** [exercism/automated-analysis#45]
I'd like to create an analyzer for Rust.

I have developed a [basic prototype](https://github.com/ZapAnton/rust-analyzer), that conforms to the Interface and does a primitive analysis of the `reverse-string` exercise (basically compares the solution with the prepared AST).
The `reverse-string` exercise was chosen instead of `two-fer`, because `two-fer` was [deemed unsuitable for the track](https://github.com/exercism/rust/issues/552) and [later deprecated](https://github.com/exercism/rust/pull/560). Currently `reverse-string` is the first core exercise.

**Comment by iHiD** [comment]
@ZapAnton Great! :) 

I have:
- Created https://github.com/exercism/rust-analyzer
- Invited you to a [team for it](https://github.com/orgs/exercism/teams/rust-analyzer)
- Sent you data on Slack
