### ISSUE TITLE
Analyzer output/deploy versioning

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/automated-analysis#47]
Separated from https://github.com/exercism/automated-mentoring-support/issues/36#issuecomment-479845734, mentioned by Richard Leurs: https://exercism-team.slack.com/archives/CFMEG1H0C/p1558970332023800

> It seems that not the lastest version of the c# analyzer is running on production. I am judging the results that run on prodction, but some solutions get different results that the current analyzer would produce. How do the analyzers on production keep in sync with the published code?

An intermediary way to supposrt this is getting the analyzer `git sha` when building / deploying an analyzer. This would then show up in the analyzer output.

> @ihid @ccare can we tag (not git tag, just tag so that we know when looking at the output) somehow the git sha when you build and deploy? That would be a nice intermediary solution.

Preferably we have something like that _in conjuction_ with a "repo" provided version, so that we can specifically tell the analyzer output which version _that analyzer_ was running on, instead of the entire repository. I propose:

We write the version of the analyzer (for that exercise), either as an incrementing number or semver
- to `analysis.out`; this is the worst because that means we need to normalise that output
- to `output.version` or `version.out` or `analysis.version` or `analysis.version.out`; probably means you can directly fetch this and show it on the 'results' page

I would suggest this "out" version is combined with the git tag.

**Comment by tehsphinx** [comment]
My suggestion:
- tag versions with git tags
- use git tags in build process to "build" it into the analyzer
- only deploy if version tag is present
- semver version tags (e.g. `v0.2.14`) -- `git sha` not necessary if we use git tags.
- analyzer should add its version to the output `analysis.json`. Creating a new file for this complicates things IMO.
- we need to be able to see which version analyzed a solution on https://exercism.io/mentor/analyses

**Comment by ErikSchierboom** [comment]
I like the suggestions made by @tehsphinx!
