### ISSUE TITLE
WIP: AST Matching (Go Track)

### ISSUE THREAD

**Issue by tehsphinx** [exercism/automated-analysis#5]
Finally got around to try some `ast` matching algorithm which can be found here: https://github.com/tehsphinx/astpatt

### The Problem

Exalysis and other algorithms with the same approach try to check solutions by finding things to improve. That is done by finding common mistakes / improvable patterns.

Those algorithms have a blind spot. If the algorithm doesn't find anything to improve it can have one of 2 reasons:
- the solution is perfect
- the solution is so far off that the algorithm doesn't find any suggestions

### The Approach

To solve this the idea is to check the solutions AST against a series of known good solutions ASTs.

### The ASTPatt (AST Pattern) package

The package can be found here: https://github.com/tehsphinx/astpatt. For now it is a prototype.

The package takes a **good solution** and **extracts** its basic **structure**. Nodes that are not defining the solutions structure are ignored. This will have to be refined with time. The system is flexible and can take different properties into account per node type.

The **extracted structure** can then be **saved to a file**. Currently it uses a JSON structure but a more edit friendly structure could be considered.

A solution that needs to be checked can then be **matched against** a list of good structures. This is done by extracting the structure of the solution and comparing it with the good structures. The comparing algorithm can be adjusted on per node level. Meaning it is not a plain `equal` comparison.

The [Tests](https://github.com/tehsphinx/astpatt/blob/master/pattern_test.go#L126) show best how the package can be used. One or more good solutions are used to get the structure from and then other solutions are tested against it:
- `ExtractPattern` extracts the pattern of a solution (as a sample to compare against)
- `MatchPatterns` or `DiffPatterns` match a solution against a list of patterns. `DiffPatterns` additionally provides a pattern diff which is mainly useful for testing.

**Comment by tehsphinx** [comment]
My thoughts on how this could work together with the suggestion algorithm:
- If the AST pattern does not match: NO APPROVAL
- If the AST pattern matches, but a TODO suggestion was added: NO APPROVAL
- If the AST pattern matches, but too many suggestions were added: NO APPROVAL
- If the AST pattern matches and only a few or no suggestions were added: APPROVAL

Loosening the first point in this list has a problematic side effect: A solution could be completely off or almost perfect and the suggestion algorithm still finds a suggestion: Then we still do not know if it is good or not. The only way I see we can avoid this is by adding the pattern of that solution to the list of good patterns, satisfying the first point in the list.

**Comment by iHiD** [comment]
So, I considered this approach, but was concerned that it would be too brittle or maybe have too many false-positives. My approach was to walk through different scenarios and then abort when a difference or unknown was found (see here: https://github.com/exercism/ruby-analyzer/blob/master/lib/analyzers/two_fer/analyze.rb#L17)

I'm not in any way convinced my approach is better but I post it purely as food for thought.

**Comment by razum2um** [comment]
@tehsphinx I think at the first step we should only focus on most clean solutions (e.g. approved without/with "nice/good/ok/handpick-word-from-current-ones" comments at once) and replacing names of variables/functions/classes/namespaces consistently -> then only mark as approved, without trying smart suggestions.

> too many false-positives

given above, @iHiD could you bring some examples?

> to walk through different scenarios

actually I also think that it is *the* way to *suggest something* - aka write code matching ast manually but I think ast pattern matching can at least suggest which solutions (except clean-accepted) are most common.

**Comment by tehsphinx** [comment]
@razum2um:

> and replacing names of variables/functions/classes/namespaces consistently -> then only mark as approved

That is kind of what this prototype is about. It walks the AST and decides what information to compare/disregard.

> without trying smart suggestions

That's what exalysis already does... no "trying" necessary 😏

**Comment by tehsphinx** [comment]
@iHiD I see your point. In the current version my algorithm might be too lax. I guess I relied very much on the suggestion-finding after to check for the kinds of things you check in your approach.

The comparing algorithm could be made much more strict easily. I think that is a matter of fine tuning to find the right balance.

The advantage of AST comparison is that
1. it is very simple to create a pattern from an existing "perfect" solution.  
2. there is no exercise specific implementation necessary

**Comment by iHiD** [comment]
Moving forward in v3, I think your approach will work really well @tehsphinx
