### ISSUE TITLE
Analyzer for Common Lisp

### ISSUE THREAD

**Issue by verdammelt** [exercism/automated-analysis#57]
Hello, I am Mark Simpson, the author, maintainer, and (maybe only) mentor of the Common Lisp track.

I'd like to experiment with an analyzer to see if it could automate some of my most common responses to exercises.

Parsing the AST of the language is simple - since programs are written in that AST itself :)

I am reviewing the [docs](https://github.com/exercism/automated-mentoring-support/tree/master/docs) and will start work on the analyzer script.

**Comment by iHiD** [comment]
Hi Mark. You have write access to https://github.com/exercism/common-lisp-analyzer :)

**Comment by iHiD** [comment]
> Parsing the AST of the language is simple - since programs are written in that AST itself :)

This is so depressing for the rest of us!

**Comment by verdammelt** [comment]
@iHiD Thanks. 

So after I create a `Dockerfile` and a `bin/analyze.sh` how to do i go about checking how it is working? How does it go from being my little toy to something actually running in production? I'm sure I'll have problems getting the Dockerfile correct -how do I see the failed attempts?

**Comment by NobbZ** [comment]
We other maintainers would help you with the dockerfile, in the most cases it is just a very thin wrapper around your compiled binary or scripts.

And to test the docker image, just play around with it using `docker run`. You will get (if you haven't already) some example solutions from the database to play with.

**Comment by iHiD** [comment]
@verdammelt Also, when you feel you're ready, you can comment [here](https://github.com/exercism/automated-mentoring-support/issues/44) and @ccare will try deploying it and feed back any issues. He can then work through things through with you on Slack in real-time.

If you 1-1 me on Slack I'll send you some files.

**Comment by verdammelt** [comment]
Thank you all.
