### ISSUE TITLE
Advice for autocomment

### ISSUE THREAD

**Issue by emcoding** [exercism/automated-analysis#59]
See Ruby/TwoFer: https://github.com/exercism/website-copy/pull/1121

For the first exercises on a track, here's my advice for commenting.

1) Name the difference between what the students is doing, and what is 'idiomatic' in the language. 
2) Use the proper terms, so students can recognize those concepts elsewhere. And can research them by themselves.  
3) Don't give the solution, but also don't explain the concept.  (In other words, give the minimal needed information that both beginners and experienced developers need to take the next step. By themselves.)
4) Give a link that shows exactly how to do the concept, in a tutorial kind of way. Meaning: showing _how_ to do things, not discussing _why_. In Ruby, that also means not linking to the official docs. 

For Ruby TwoFer these guidelines translate to:
Ruby has no problem with the way you are composing the string ('string concatenation'). However, a more idiomatic way to compose a string in Ruby is with [string interpolation](http://ruby-for-beginners.rubymonstas.org/bonus/string_interpolation.html).

**Comment by kytrinyx** [comment]
This are great recommendations when it comes to mentoring the first few exercises on a track.

I would also add: keep it relatively short, avoiding a wall of text or overwhelming them with advice. If they have a great experience in the first exercise, they'll come back and you'll have many more opportunities to provide feedback on all of the things that you noticed.

**Comment by kytrinyx** [comment]
I might split up number 3 above, as they seem to be motivated by different things.

"Don't give the solution" is general advice for all Exercism mentoring. Learning sticks when people discover the answer for themselves. That's a tremendously exhilarating experience, and the emotional kick makes it memorable.

"Don't explain the concept" I think is unclear here, but I understand it to mean: "don't go in depth about the underlying mechanisms of compilers and things". In this case it's more about this being one of the first exercises in the language track, and at this stage feedback is more helpful if it's shorter and more directive.

I would also add one more guideline: you should provide a link only for more in-depth exploration. The person should be able to understand what you mean from the answer directly, without following the link.

**Comment by kytrinyx** [comment]
Hm, I have one more thing...

> "Don't give the solution" is general advice for all Exercism mentoring. Learning sticks when people discover the answer for themselves. That's a tremendously exhilarating experience, and the emotional kick makes it memorable.

I think this is true in general, but only if the discovery actually would trigger a dopamine hit. So in the case of ruby concatenation, I think showing what it looks like makes total sense. I really mean "don't give the solution" if there really is some discovery that can be made or some thinking that needs to happen. E.g. if someone solves raindrops with all if statements, that's perfectly reasonable, but can they think of a way to not use a conditional?
