### ISSUE TITLE
Upgrade analysers for new comments

### ISSUE THREAD

**Issue by iHiD** [exercism/automated-analysis#62]
When you're ready to deploy approval + comments, please could you add a comment with a PR that needs to be merged to comply with the latest spec of the analyser with `approve` and comments. If it's already master, pls say that.

- [ ] Ruby
- [ ] Go

**Comment by iHiD** [comment]
Ruby was this [horrible commit](https://github.com/exercism/ruby-analyzer/commit/4a39f3a25b6ee609243e9eaf785f19661ceae15c).

**Comment by tehsphinx** [comment]
Go analyzer is ready for `deploy approval + comments` with version `0.4.0`.
That is for exercises `two-fer` and `hamming`. `raindrops` can be enabled, there just won't be any comments created by the analyzer, yet.

**Comment by ErikSchierboom** [comment]
The C# analyzer is updated for the new statuses and is ready for comments (using the `master` branch). The last thing that needs to be done, is that the comment PRs should be merged:

- https://github.com/exercism/website-copy/pull/1125
- https://github.com/exercism/website-copy/pull/1126
- https://github.com/exercism/website-copy/pull/1127
- https://github.com/exercism/website-copy/pull/1128

**Comment by SleeplessByte** [comment]
(already on master) #64
