### ISSUE TITLE
[Update To Deploy] Java

### ISSUE THREAD

**Issue by jmrunkle** [exercism/automated-analysis#65]
Please specify the track. The most recent tag will be deployed.

java-analyzer has been updated with "approve" comments

**Comment by ccare** [comment]
Fantastic, thanks!

When you get a second, would you be able to help me find some example solutions that we can run-through? - I'd like to do an end-to-end smoke test before we replay lots of solutions through the commenting version.

**Comment by ccare** [comment]
Looks like we have a glitch with some of the comment copy... https://exercism.io/mentor/analyses/7281

**Comment by ccare** [comment]
From what I understand, it looks like we either need to rename this file https://github.com/exercism/website-copy/blob/master/automated-comments/java/two-fer/use_ternary_operator.md to `use_ternary_expression` or change the reference in the analyser.

**Comment by jmrunkle** [comment]
Doh, you are correct. Let me send a PR to fix the analyzer (since the "operator" is probably more correct here).

**Comment by jmrunkle** [comment]
https://github.com/exercism/java-analyzer/pull/15 - once that goes in this should be good to go

**Comment by ccare** [comment]
Thanks!

**Comment by ccare** [comment]
All sorted and deployed. Thanks. Seen a couple go well. I'll reprocess the backlog in a bit.

**Comment by ccare** [comment]
> I'll reprocess the backlog in a bit.

Actually I'll probably do that another day. It's getting late here. I'll leave this open to remind me, but thanks @jmrunkle !

**Comment by jmrunkle** [comment]
Thank you @ccare - glad we could get this going.

**Comment by ccare** [comment]
We were up deploying a new logging feature anyway, so I did push the queue through. Backlog is now down from 72 to 44, and mostly approvals from what I can see. That's saved a huge chunk of mentor time.
