### ISSUE TITLE
[Update To Deploy] Scala

### ISSUE THREAD

**Issue by ricemery** [exercism/automated-analysis#67]
Scala Track - updates to support disapprove comments for two-fer.

https://github.com/exercism/scala-analyzer/releases/tag/v0.1.2

https://github.com/exercism/website-copy/pull/1148

**Comment by iHiD** [comment]
Thanks :) It's worth noting that we won't honour disapprove comments for the next few weeks. But we can safely release this anyway.

**Comment by ccare** [comment]
Thanks @ricemery, the analyzer should now be live. I did a quick smoke test and it looks good.

**Comment by ricemery** [comment]
Thanks!
