### ISSUE TITLE
auto-mentoring after approval

### ISSUE THREAD

**Issue by tehsphinx** [exercism/automated-analysis#68]
Currently there is **no acknowledgement or feedback** of any kind if a solution was auto-approved (with or without comments) and then a new iteration was added by the student.

Especially if it was auto-approved with comments, this leaves the student **un-mentored in their effort to improve the solution** further.

We already had a short discussion on slack on this subject. My take on things is:

>In my mind the analyzer would run again, so the student got feedback on whether a suggestion was successfully implemented or not.
>As a student I would expect the analyzer (as I know it’s a bot) to just repeat itself on unsolved suggestions, removing the comments that were solved and adding new comments if there are new things to improve in my changes.

### Example Case
Here an example where I think it is critical the auto-mentoring tool would run again on the new iteration as it was made worse while trying to improve it:
https://exercism.io/mentor/solutions/6334132caa9e4b1482acb7252d6cf823

The first iteration takes an index (to get bytes from a string) that skips bytes if multi-byte characters get involved, the second compares `runes` (characters) with `bytes` -- which is definitely worse. But no more feedback is provided on the second iteration.

**Comment by iHiD** [comment]
This ceases to matter in v3, so closing.
