### ISSUE TITLE
[Update To Deploy] Go v0.4.2

### ISSUE THREAD

**Issue by tehsphinx** [exercism/automated-analysis#71]
Update to `Go` analyzer.

This adds (more) comments to `raindrops` exercise and should approve a lot more exercises.

This depends on the comments being merged into `website-copy` first:
- [x] exercism/website-copy#1216

**Comment by iHiD** [comment]
@ccare This can be deployed now.

**Comment by ccare** [comment]
This is now deployed - I replayed a couple of sample solutions and I saw a raindrops one change from refer to mentor to approve. So all looking great right now. Thanks @tehsphinx !

**Comment by tehsphinx** [comment]
Looking good.

**Comment by iHiD** [comment]
Thanks both! I'm closing this for housekeeping :)
