### ISSUE TITLE
[Update To Deploy] - Scala

### ISSUE THREAD

**Issue by ricemery** [exercism/automated-analysis#72]
Please deploy the Scala Analyzer. The analyzer has been updated to support the leap exercise.
The version to deploy is 0.1.4.

Note that I have not created website copy for this exercise. The "approve" case will never generate any messages to the users. The only messages would come from - refer_to_mentor or "disapprove". Will work on creating the content next.

Thanks

**Comment by ccare** [comment]
I tried this, but after deployment we saw a lot of two-fes change their diagnosis from approve back to refer_to_mentor.

New analyser https://exercism.io/mentor/analyses/16800
Old analyser https://exercism.io/mentor/analyses/16816

I've temporarily switched back to the old implementation.

**Comment by ricemery** [comment]
Sorry about that @ccare .

I have pushed up some changes that should fix the problem. The new version is 0.1.5.

**Comment by ccare** [comment]
That's deployed and looking fine now. I'll now enable the runtime to support `leap`

**Comment by ccare** [comment]
Looking good now, I've replayed a number of existing `leap` solutions and it's all looking great (as far as I can see anyway). Some examples:

- https://exercism.io/mentor/analyses/16994
- https://exercism.io/mentor/analyses/16993
- https://exercism.io/mentor/analyses/16992
- https://exercism.io/mentor/analyses/16991

**Comment by ccare** [comment]
@ricemery it's all looking good. Thanks!
