### ISSUE TITLE
[Update To Deploy] C#

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/automated-analysis#74]
Please deploy the latest C# analyzer. It doesn't use tags at the moment, so the deploy can be made from the `master` branch.

**Comment by ccare** [comment]
Hi @ErikSchierboom , I gave it a go, but when I pushed it live (and replayed a couple of solutions) things just started to fail, so I rolled back.

![image](https://user-images.githubusercontent.com/441154/63290504-6aea7780-c2b9-11e9-9eb3-7b99fab1bd41.png)

**Comment by ccare** [comment]
Looking at it, it looks like it might be a simple fix, I got this error in the logs

```
container_linux.go:344: starting container process caused "exec: \"bin/analyze.sh\": permission denied"
raw_output.err (END)
```

**Comment by ErikSchierboom** [comment]
Ah, the shell script did not have an executable bit set. Sorry about that!

I've just pushed a [new commit](https://github.com/exercism/csharp-analyzer/commit/008f6d248538149f413118ccfbc21ccd05d919b1) that fixes this. Hopefully this will solve the issue.

**Comment by ccare** [comment]
Hi @ErikSchierboom, sorry for the delay, but I've shipped that and it looks good to me now. Are there any specific examples/solutions I should try and and replay as a smoke test?

Feel free to close this issue if you're happy :)

**Comment by ErikSchierboom** [comment]
Awesome! Could you replay https://exercism.io/mentor/analyses/19131?

**Comment by ccare** [comment]
It looks good to me. Here are the before/after states before the replay.

```
{
  "status": "disapprove",
  "comments": [
    {
      "params": {
      },
      "comment": "csharp.general.has_compile_errors"
    }
  ]
}
```

```
{
  "status": "disapprove",
  "comments": [
    {
      "params": {
        "name": "Speak",
        "signature": "public static string Speak(string name)"
      },
      "comment": "csharp.general.invalid_method_signature"
    },
    {
      "params": {
      },
      "comment": "csharp.two-fer.use_single_formatted_string_not_multiple"
    },
    {
      "params": {
        "name": "kisi"
      },
      "comment": "csharp.two-fer.use_default_value"
    }
  ]
}
```

**Comment by ccare** [comment]
@ErikSchierboom does that mean it's OK now?

**Comment by ErikSchierboom** [comment]
@ccare Yep, it's ok then!
