### ISSUE TITLE
[Update To Deploy] Java analyzer

### ISSUE THREAD

**Issue by Smarticles101** [exercism/automated-analysis#75]
Please deploy the latest Java analyzer on the `master` branch. We've just merged an analyzer for the hamming exercise and will add comments shortly.

**Comment by jmrunkle** [comment]
May want this to wait until https://github.com/exercism/website-copy/pull/1262 actually goes in otherwise the comments will not be in place.

**Comment by Smarticles101** [comment]
no, the comments are updated independently from the analyzer iirc

**Comment by iHiD** [comment]
Hi both. So the comments need to be in place before the analyzer is deployed, else the analyses will error (due to missing comments). Saying that, erroring doesn't really have massive side-effects. The only real thing is that for disapprove comments, the mentors might not understand why it's being disapproved and what to do if the comments are missing.

**Comment by jmrunkle** [comment]
Thanks for confirming - that was what I recalled when we were deploying the twofer analyzer.

**Comment by ccare** [comment]
I've built the image for this, so whenever the comments are merged, it'll be good to release.

**Comment by SleeplessByte** [comment]
@ccare good to go! I just merged it in.

**Comment by jmrunkle** [comment]
Thanks @SleeplessByte - @ccare just update once you release it so that I can check the analyses dashboard.

**Comment by ccare** [comment]
@jmrunkle I've deployed this, and re-run a few analyses through - all looking good so far (no change or breaks for existing exercises :) ).

There are 30ish hamming iterations that are in a good state to be sent through the analyser, these should provide a good smoke test. However, before that'll work, we'll need a quick PR on here https://github.com/exercism/analyzer-orchestrator/blob/59af78310f8cb9cb3487d3b6f3294a0354366321/lib/orchestrator/analyze_iteration.rb#L12 to enable the exercise for static analysis. I can prepare and release that, but figured you might want to be control when this gets enabled. Let me know what you want to do.

**Comment by jmrunkle** [comment]
@ccare Feel free to proceed (I know we are in different timezones anyway). I don't need manual control over when it gets enabled.

**Comment by ccare** [comment]
Cool! I will let you know how it goes.

**Comment by jmrunkle** [comment]
Also, is there something we need to do to run it against the existing queue? I assume that is part of the process, but just wanted to be certain.

**Comment by iHiD** [comment]
> Also, is there something we need to do to run it against the existing queue?

@ccare I think you have a script to do this, but let me know if not and I'll put one together for you

**Comment by ccare** [comment]
There is indeed a script for this... it resides at https://github.com/exercism/scripts/blob/master/publish_batch_to_analyze.rb and very good it is too :)

@Smarticles101, @jmrunkle I've re-run them through, and it's all looking great! Thanks all.

<img width="956" alt="Screenshot 2019-09-04 at 11 53 43" src="https://user-images.githubusercontent.com/441154/64249210-124ae980-cf0b-11e9-8c19-3c38ffa9f352.png">

Given that I've seen the analyser happily returning all the various states, I'll close this issue now, but do reopen if you think anything needs is wrong. Thanks again.

**Comment by jmrunkle** [comment]
I just checked it over myself and the analyses seem to be correct. Thanks!

**Comment by ccare** [comment]
Cool!
