### ISSUE TITLE
Move analysis.json into a different folder than the solution

### ISSUE THREAD

**Issue by iHiD** [exercism/automated-analysis#77]
At the moment the analysis.json is written into a folder with the solution code. I see this as a possible attack vector as solutions could be submitted with it already present, and parsing it could lead to vulnerabilities. I therefore want us to write the analysis.json to a different directory. I am thinking the following structure would be sensible:

```
/iteration/[SOLUTION_FILES]
/analysis.json
/analysis.out
```

Other than voicing frustration at the hassle of having to change their analyzers, does anyone have any feedback?

**Comment by SleeplessByte** [comment]
Fine with me, but preferably we want to receive _both_ the input dir _and_ output dir, so that "root" can remain "unwritable"?

**Comment by ErikSchierboom** [comment]
> Fine with me, but preferably we want to receive both the input dir and output dir, so that "root" can remain "unwritable"?

It seems like a great idea anyway to be explicit about where to save the files to, as we can then change it easily later on if we should so decide to.

It seems like this should also apply to the proposed test runner interface, right?

**Comment by iHiD** [comment]
Having chatted to @ccare, I don't think it hugely matters whether root is writable too or not, as it's totally scoped for this one solution.

However I do think it would be better to have:
```
/iteration/[SOLUTION_FILES]
/output/analysis.json
/output/analysis.out
```

We will continue to pass in arg2 as we currently do, but then the input will be `iteration` and output will be `output` or something. I don't think we see much benefit in passing in an extra arg.

**Comment by ErikSchierboom** [comment]
I don't particularly mind not having an extra argument, I can always add it to my own analyzer and have it default to `/output` if it's not provided.

**Comment by ccare** [comment]
From our earlier conversation, I was more leaning to something like

`/mnt/exercism/iteration` and `/mnt/exercism/result`, so subdirs of the original mount, not a new /output root mount.

**Comment by SleeplessByte** [comment]
I didn't particularly mean that root has to stay unwritable but exactly that this discussion here already shows we might want to change the output dir along the way 😅

**Comment by iHiD** [comment]
So two possibilites I see here. 
1. Pass in a dir and then have two subdirectories underneath that (`iteration`/`output`) that the analyzer reads/writes from. (🎉)
1. Pass in two arguments: an iteration and an output dir. (🚀)

Vote using the emoji above on this post. If we don't have a consensus, we can discuss further.

Once we agree this, I'm tempted to turn off all the analyzers until people update their specs to match to get us aligned quickly. As I think it's a 10min job to update the analyzer to match the new spec, hopefully people can do it quite quickly. I'd rather not have code to support both specs at once Do people agree?

**Comment by ErikSchierboom** [comment]
>  I'd rather not have code to support both specs at once Do people agree?

I don't mind updating the analyzer.

**Comment by tehsphinx** [comment]
We could set the iteration and output dir to the same folder at first, for all analysers to switch, then implement the separation.

**Comment by iHiD** [comment]
@tehsphinx  Excellent idea.

**Comment by iHiD** [comment]
This got done.
