### ISSUE TITLE
[New Analyzer] Elixir

### ISSUE THREAD

**Issue by neenjaw** [exercism/automated-analysis#79]
Hi,

My name is Tim Austin (@neenjaw) and I am a mentor on the elixir track and have contributed to the elixir track repository. 

I would like to implement an elixir analysis tool to provide automated feedback. I have a prototype located in a [public repo](https://github.com/neenjaw/proto-elixir-analyzer).  

The analyzer implements a domain specific language which describes features of programs (detected through AST analysis and pattern matching) and then returns the feedback according an older spec of the analyzer result JSON. 

At the moment, the prototype implements the `two-fer` problem, but it is designed in such a way that extending it to the core problems should be possible as I am unsure of twofer becoming part of the core elixir track. 

While not yet in publishable state, I wanted to open it up to allow others to contribute if interested and for it to be a project for myself during hacktoberfest. 

I don't see this track having an analyzer yet, but if there is something already started would love to contribute.

**Comment by SleeplessByte** [comment]
Great! I only have one question:

Is this analyzer _also_ running the tests, as per the README.md? Because if it is, it shouldn't. We want running tests to be separated from running analysis. But I might read it with bias and you meant "test for analysis" instead of "exercise tests".

**Comment by neenjaw** [comment]
That is a good question. It can but it doesn't have to when doing static
analysis. It does have to "compile" in order to generate the AST, but not
run any exercise code.

At the moment, the testing is a run time option, so it can be disable. I
cobbled together this prototype together before I had decided where it
might fall in the eco system, so was experimenting with a couple things.

In the end, it may be more simple to split it into two applications as they
are loosely coupled. Then there is a better distinction between the analyze
and test functions.

It certainly can be split before the initial commit to the repo to better
focus its intent.

**Comment by neenjaw** [comment]
That is a good question. It can but it doesn't have to when doing static analysis. 

It does have to "compile" in order to generate the AST, but not run any exercise code.

At the moment, the testing is a run time option, so it can be disable. I cobbled together this prototype together before I had decided where it
might fall in the eco system, so was experimenting with a couple things.

In the end, it may be more simple to split it into two applications as they are loosely coupled. Then there is a better distinction between the analyze and test functions.

It certainly can be split before the initial commit to the repo to better focus its intent and match the focus of the project

**Comment by neenjaw** [comment]
https://github.com/neenjaw/proto-elixir-analyzer/tree/elixir-analysis is a branch of the prototype which only runs the static analysis, the testing features have been removed.  I would probably go forward with this version

**Comment by iHiD** [comment]
I've added the repo here: https://github.com/exercism/elixir-analyzer. I've also invited you to the GitHub org, which will give you access to that.

Finally, I've also added @nobbz to the team, as someone who might be able to review code etc, and who you can buddy up with if needed :)

You might also be interested in helping on the test-runner, which I believe @nobbz was hoping to make a start on soon. Let me know if so, and I can add you to the team.

**Comment by NobbZ** [comment]
I'm planning on preparing a README.md and a CONTRIBUTING.md during the weekend, hoping to lure someone during hacktoberfest :D

**Comment by SleeplessByte** [comment]
You can copy (parts) from the ones we have at the [javascript-analyzer](https://github.com/exercism/javascript-analyzer/blob/master/CONTRIBUTING.md) and [javascript-track](https://github.com/exercism/javascript/blob/17ed7e7487fd2a6f243b9bd304797e99dc4f0fa2/CONTRIBUTING.md)!

**Comment by neenjaw** [comment]
Sure, I'd like to help with that too. There is a piece of code in that first repo which is an ExUnit CLI formatter which is all we need to turn ExUnit output into JSON for output.

**Comment by iHiD** [comment]
@neenjaw I've added you to the test-runner team too.
