### ISSUE TITLE
[New Analyzer] C#

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/automated-analysis#8]
I'd love to create a C# analyzer. There already is a prototype at https://github.com/erikschierboom/exercism.analyzers.csharp, so I hope goes some way towards my credentials :)

**Comment by iHiD** [comment]
Thanks @ErikSchierboom! Very excited about your prototype and work.

I've created [a repo](https://github.com/exercism/csharp-analyzer) for you, and set up a new team (@exercism/csharp-analyzer) for you with write-permissions :)

I have also sent you privately the first iterations of the most recent 500 two-fers in C#.
