### ISSUE TITLE
[New Representer] Common Lisp

### ISSUE THREAD

**Issue by verdammelt** [exercism/automated-analysis#92]
I am the maintainer of the Commm Lisp language track.  As part of v3 maintainer activities I'll need to write a representer. This is the first step - getting a repo for it.

**Comment by ErikSchierboom** [comment]
Something for @iHiD to do :)

**Comment by iHiD** [comment]
Great. Here you go: https://github.com/exercism/common-lisp-representer

Have fun! :)
