### ISSUE TITLE
[New analyzer] Clojure

### ISSUE THREAD

**Issue by bobbicodes** [exercism/automated-analysis#98]
I'd like to start working on this. I've been exploring some ideas on different approaches, and definitely worth looking at are [tools.reader](https://github.com/clojure/tools.reader) and [tools.analyzer](https://github.com/clojure/tools.analyzer), as well as the [Small Clojure Interpreter](https://github.com/borkdude/sci). A solution leveraging all of these could be fantastic!

One advantage of Clojure, being a Lisp, is already written as structured data. Transforming Clojure code into an AST is trivial compared to other languages because it consists almost entirely of nested lists.

**Comment by iHiD** [comment]
Exciting! :) https://github.com/exercism/clojure-analyzer

**Comment by iHiD** [comment]
Also https://github.com/exercism/clojure-representer
